### ISSUE TITLE
Not working with Entity Framework 2.2

### ISSUE THREAD

**Issue by peef** [BorisWilhelms/azure-function-dependency-injection#28] opened 2019-01-17 12:05 UTC
Adding DB context when `Microsoft.EntityFrameworkCore.SqlServer` v2.2.1 is used raise this error during app start:

_A host error has occurred
Willezone.Azure.WebJobs.Extensions.DependencyInjection: Method not found: 'Microsoft.Extensions.DependencyInjection.IServiceCollection Microsoft.Azure.WebJobs.IWebJobsBuilder.get_Services()'._

When downgrade to EF v2.1.4 then register DB context is OK.

**Comment by BorisWilhelms** [comment] 2019-03-01 17:01
Duplicate of #26

**Closed as completed by BorisWilhelms** 2019-03-01 17:01 UTC
